// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Team struct {
	ID        uuid.UUID
	Name      string
	LeaderID  uuid.UUID
	EventID   uuid.UUID
	IsReady   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TeamInvitation struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	InviterID     uuid.UUID
	InvitedUserID uuid.UUID
	Status        string
	CreatedAt     sql.NullTime
	RespondedAt   sql.NullTime
}

type TeamMember struct {
	ID       uuid.UUID
	TeamID   uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt sql.NullTime
}
