// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type NotificationType string

const (
	NotificationTypeSYSTEM      NotificationType = "SYSTEM"
	NotificationTypeSCOREUPDATE NotificationType = "SCORE_UPDATE"
	NotificationTypeTEAMINVITE  NotificationType = "TEAM_INVITE"
	NotificationTypeEVENTUPDATE NotificationType = "EVENT_UPDATE"
	NotificationTypeGENERAL     NotificationType = "GENERAL"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type SenderType string

const (
	SenderTypeUNKNOWNSENDER SenderType = "UNKNOWN_SENDER"
	SenderTypeADMIN         SenderType = "ADMIN"
	SenderTypeORGANIZER     SenderType = "ORGANIZER"
)

func (e *SenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SenderType(s)
	case string:
		*e = SenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for SenderType: %T", src)
	}
	return nil
}

type NullSenderType struct {
	SenderType SenderType
	Valid      bool // Valid is true if SenderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSenderType) Scan(value interface{}) error {
	if value == nil {
		ns.SenderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SenderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSenderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SenderType), nil
}

type Notification struct {
	ID         uuid.UUID
	SenderID   uuid.UUID
	SenderType SenderType
	UserID     uuid.NullUUID
	IsPublic   bool
	Title      string
	Body       string
	Type       NotificationType
	CreatedAt  sql.NullTime
}
