// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    sender_id,
    sender_type,
    user_id,
    is_public,
    title,
    body,
    type
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    sender_id,
    sender_type,
    user_id,
    is_public,
    title,
    body,
    type,
    created_at
`

type CreateNotificationParams struct {
	SenderID   uuid.UUID
	SenderType SenderType
	UserID     uuid.NullUUID
	IsPublic   bool
	Title      string
	Body       string
	Type       NotificationType
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.SenderID,
		arg.SenderType,
		arg.UserID,
		arg.IsPublic,
		arg.Title,
		arg.Body,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.SenderType,
		&i.UserID,
		&i.IsPublic,
		&i.Title,
		&i.Body,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
